import React from 'react'

export default function About() {
  return (
    <div>
      <h2 className='text-center' style={{marginTop:"60px"}}>This is about page of my site</h2>
      <h5 style={{marginTop:"100px"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Possimus reiciendis reprehenderit distinctio veniam perspiciatis assumenda pariatur animi aperiam, accusamus libero perferendis, eligendi voluptatem accusantium quaerat, ab soluta repellendus quos aspernatur nulla deserunt nam quas vitae! Sunt ipsam temporibus sed maiores modi esse accusamus aperiam totam alias vitae dolore animi autem, vel voluptas at corrupti tempora exercitationem recusandae dolor illo fugit. Sequi sint quia quaerat consequuntur eligendi expedita, est id vel voluptatum harum culpa sit perferendis cupiditate cum, minima iste laborum. Provident, a vero? Nesciunt, iusto minus asperiores architecto placeat quod dolorum incidunt aperiam eaque quidem numquam neque, expedita provident voluptatibus velit laboriosam doloremque, nihil nobis. Beatae aperiam non harum unde ullam cupiditate mollitia tempora. Voluptate veritatis odio cupiditate quisquam debitis inventore, porro omnis maxime corrupti deserunt corporis fugiat, odit, laboriosam delectus nihil suscipit nostrum recusandae ad explicabo? Fugit libero vero odit repellendus, tempora officiis voluptate suscipit illum quae asperiores magnam voluptatum iure animi, eum ratione non. Sunt quas est esse fugiat exercitationem odio magnam possimus illum itaque eos nemo, natus quo accusantium aliquid totam blanditiis iure obcaecati pariatur. Provident nisi alias, expedita delectus veniam tenetur praesentium dolorum natus, repellendus minima numquam voluptatem fuga vero molestias. Tenetur accusamus maxime quidem tempora aliquam similique maiores sint, excepturi numquam obcaecati asperiores voluptates dignissimos dicta unde quod possimus enim harum officia. Quia, mollitia neque reiciendis omnis ex necessitatibus inventore itaque sapiente, perferendis aspernatur quibusdam voluptatibus aut ullam dolores adipisci optio nihil nobis officia. Debitis cumque, doloremque nam voluptatibus eaque culpa. Culpa voluptatibus similique aut, laborum magnam quod expedita minus hic quidem fugit nam nemo iure. Voluptates eligendi vel porro exercitationem dicta autem perferendis ipsam accusamus minima ad quas quisquam at maxime voluptatum, dignissimos est tempora consectetur quos nesciunt qui laboriosam veritatis quod saepe blanditiis! Iusto repudiandae expedita atque magnam assumenda alias, nostrum cum quos.</h5>
    </div>
  )
}
